require 'brooklyn/shipping_labels/stamps_service'
require 'brooklyn/shipping_labels/test_service'
require 'ladon'

module Brooklyn
  # The interface for external shipping label services.
 module ShippingLabels
    # Instantiates and returns an instance of a shipping label service. In test environments, this is a +TestService+
    # that does not make any network calls to external systems. In all other environments it returns a +StampsService+.
    #
    # @param [OpenStruct] config the config object for the shipping label service
    # @return [Brooklyn::ShippingLabels::ServiceBase]
    # @see Brooklyn::ShippingLabels::TestService
    # @see Brooklyn::ShippingLabels::StampsService
    def self.create(config)
      if Rails.env.test? || Rails.env.integration?
        TestService.new(config)
      else
        StampsService.new(config)
      end
    end

    # A simple value class representing a label generated by a shipping label service.
    class Label < Ladon::Model
      attr_accessor :tracking_number, :url, :tx_id, :document
    end
  end
end
