development:
  "collections,facebook,tracking,notification,email,contacts,reap_guests,orders,sellers,network,network_slow,photos,photo_processing_bulk,photo_processing,credits,hooks,index,stories,sharing,users,listings,tags,follows,autofollow,shipments,connection_digest_email,payments,facebook_announce,feed_builds,scheduled": 1
staging:
  collections: 1
  contacts: 1
  credits: 1
  email: 1
  facebook: 1
  facebook_announce: 1
  hooks: 1
  index: 1
  photos: 1
  photo_processing: 2
  photo_processing_bulk: 2
  network: 1
  network_slow: 1
  notification: 1
  orders: 1
  sellers: 1
  tracking: 1
  reap_guests: 1
  stories: 1
  sharing: 1
  users: 1
  listings: 1
  tags: 1
  follows: 1
  autofollow: 1
  shipments: 1
  connection_digest_email: 1
  payments: 1
  feed_builds: 1
  scheduled: 1
production:
  collections: 1
  contacts: 1
  credits: 1
  email: 2
  facebook: 6
  facebook_announce: 2
  hooks: 1
  index: 2
  photos: 2
  photo_processing: 2
  network: 2
  network_slow: 1
  notification: 2
  orders: 1
  sellers: 1
  tracking: 6
  reap_guests: 1
  stories: 2
  sharing: 2
  users: 4
  listings: 2
  tags: 2
  follows: 6
  autofollow: 2
  shipments: 1
  connection_digest_email: 1
  payments: 1
  feed_builds: 1
  scheduled: 1
